
ERROR:root:Traceback (most recent call last):
  File "c:/assorted-projects/thesis/trial codes/exception logging.py", line 6, in <module>
    print(4/0)
ZeroDivisionError: division by zero

